### ISSUE TITLE
fetch_example_data will fail with error when using RESSPECT installed from PyPI

### ISSUE THREAD

**Issue by drewoldag** [LSSTDESC/RESSPECT#33]
To reproduce: 

1. Create new environment
2. `pip install resspect`
3. Run `fetch_example_data`

> Data unpacked into directory: /Users/drew/Library/Caches/resspect/SIMGEN_PUBLIC_DES
Traceback (most recent call last):
  File "/Users/drew/opt/miniconda3/envs/scratch/bin/fetch_example_data", line 8, in <module>
    sys.exit(fetch_example_data())
  File "/Users/drew/opt/miniconda3/envs/scratch/lib/python3.10/site-packages/resspect/scripts/fetch_example_data.py", line 36, in fetch_example_data
    os.symlink(original_directory, target_dir, target_is_directory=True)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/drew/Library/Caches/resspect/SIMGEN_PUBLIC_DES' -> '/Users/drew/opt/miniconda3/envs/scratch/lib/python3.10/data/SIMGEN_PUBLIC_DES'

**Comment by drewoldag** [comment]
I believe that I would advocate for the fix where we update the various locations that are hard coded to look for `.../data/SIMGEN_PUBLIC_DES` and replace those with the dynamically generated `<user_cache>/resspect/SIMGEN_PUBLIC_DES`. 

And if that programmatically defined directory is not found, then prompt the user to run `fetch_example_data`.

**Comment by drewoldag** [comment]
It seems like most of the places where we're looking for the hardcoded directory is in the documentation actually. There is one place in `build_cannondical_snpcc.py` that defines `data_dir = '~/data/...'`, so we would need to update that as well.
